### ISSUE TITLE
Error: Cannot find module 'strava-v3'

### ISSUE THREAD

**Issue by fbr-github** [fishion/StravaImporter#4]
What should I do?

internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'strava-v3'
Require stack:
- /vagrant/StravaImporter-main/lib/strava-client.js
- /vagrant/StravaImporter-main/lib/strava.js
- /vagrant/StravaImporter-main/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/vagrant/StravaImporter-main/lib/strava-client.js:3:20)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/vagrant/StravaImporter-main/lib/strava-client.js',
    '/vagrant/StravaImporter-main/lib/strava.js',
    '/vagrant/StravaImporter-main/index.js'
  ]
}

**Comment by fbr-github** [comment]
Now I called `npm install strava-v3` but the error remains after I retry `node index.js`

**Comment by chadlwilson** [comment]
Did you do a blanket `npm install` for all dependencies as in [the README](https://github.com/fishion/StravaImporter/blob/main/README.md#install-node-etc-and-package-dependencies)?

**Comment by fbr-github** [comment]
> 
> 
> Did you do a blanket `npm install` for all dependencies as in [the README](https://github.com/fishion/StravaImporter/blob/main/README.md#install-node-etc-and-package-dependencies)?

yes, I did

**Comment by fbr-github** [comment]
vagrant@vagrant:/vagrant$ npm install
npm WARN saveError ENOENT: no such file or directory, open '/vagrant/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/vagrant/package.json'
npm WARN request-promise@4.2.6 requires a peer of request@^2.34 but none is installed. You must install peer dependencies yourself.
npm WARN request-promise-core@1.1.4 requires a peer of request@^2.34 but none is installed. You must install peer dependencies yourself.
npm WARN vagrant No description
npm WARN vagrant No repository field.
npm WARN vagrant No README data
npm WARN vagrant No license field.

audited 53 packages in 1.414s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

v

**Comment by fbr-github** [comment]
vagrant@vagrant:/vagrant/StravaImporter-main$ npm install
npm WARN stravaimporter@1.0.0 No repository field.

npm ERR! code EPROTO
npm ERR! syscall symlink
npm ERR! path ../sshpk/bin/sshpk-conv
npm ERR! dest /vagrant/StravaImporter-main/node_modules/.bin/sshpk-conv
npm ERR! errno -71
npm ERR! EPROTO: protocol error, symlink '../sshpk/bin/sshpk-conv' -> '/vagrant/StravaImporter-main/node_modules/.bin/sshpk-conv'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2020-12-30T15_42_03_648Z-debug.log
vagrant@vagrant:/vagrant/StravaImporter-main$

**Comment by fbr-github** [comment]
sorry, I don't have an idea what these error messages mean

**Comment by chadlwilson** [comment]
No idea about what Vagrant box you are using or your host operating system, but it seems like the file system has issues, and is unable to create symbolic links which is critical for nodejs/npm to be able to install dependencies correctly.

Taking a wild guess, if you are running it on a Windows host and using a shared folder back to Windows you will have issues with symlinks, unless you enable various options on the shared folder; run as admin etc. If I recall correctly, it is painful. You can probably google and find possible solutions.

Alternatively could try git cloning into a non-shared folder inside the VM instead; or if you know Docker; use the Dockerfile someone has contributed to the repo instead of a Vagrant VM.

**Comment by fbr-github** [comment]
@chadlwilson: yeah, thank you very much, that hint about symlinks with vagrant did help! I searched a bit on stackoverflow and came across the solution to just call `npm install --no-bin-links` and that worked fine, and now I was able to start  `node index.js` and I also uploaded a test tcx file of my swimming workouts. So I think this ticket can be closed now.
